#!/bin/sh
update() {
  DIR="pixelir*.coffee"
  allhash=""
  for filepath in ${DIR}; do
    hash=`openssl sha256 -r ${filepath} | awk '{print $1}'`
    allhash=${allhash}${hash}
  done
  echo ${allhash}
}

INTERVAL=1
last=""
while true; do
	sleep $INTERVAL
	current=`update`
	if [ "$last" != "$current" ]; then
    date=`date +"%Y.%m.%d %H:%M:%S"`
		cat pixelir*.coffee | coffee -bMc -s > pixelir.js
    echo ${date}": compiled."
		last=$current
  fi
done

